# -*- coding: utf-8 -*-
"""康复训练动作库人工整理

数据源：健身动作百科 + 《运动训练学》教材
性质：公共运动学知识
输出：output/rehab_exercises.json

为康复模块补充 goal_type（增肌/减脂/康复/维持/柔韧）标签的动作库
"""

import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

# 增肌动作（muscle_gain）
MUSCLE_GAIN_EXERCISES = [
    {
        "name": "俯卧撑", "category": "力量训练", "duration": "4 组 × 12 次",
        "level": "进阶", "minutes": 10, "goal_type": "muscle_gain",
        "muscle_group": "chest", "equipment": "bodyweight",
        "calories_burn_per_min": 7,
        "steps": ["双手撑地与肩同宽", "身体保持一条直线", "屈肘下降至胸部接近地面",
                  "推起回到起始位置"],
        "caution": "核心收紧，避免塌腰或翘臀",
        "focus": "胸肌、三角肌前束、肱三头肌",
        "benefits": ["增强上肢力量", "改善胸部线条", "提升核心稳定性"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "哑铃弯举", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 8, "goal_type": "muscle_gain",
        "muscle_group": "arms", "equipment": "dumbbell",
        "calories_burn_per_min": 6,
        "steps": ["双手持哑铃自然下垂", "上臂保持固定", "屈肘将哑铃举至肩部",
                  "缓慢下降回到起始位置"],
        "caution": "避免身体晃动借力，肘部固定",
        "focus": "肱二头肌",
        "benefits": ["增强手臂力量", "改善手臂线条"],
        "video_minutes": 2,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "深蹲", "category": "力量训练", "duration": "4 组 × 15 次",
        "level": "进阶", "minutes": 12, "goal_type": "muscle_gain",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 8,
        "steps": ["双脚与肩同宽站立", "缓慢屈膝下蹲", "大腿与地面平行",
                  "站起回到起始位置"],
        "caution": "膝盖不超过脚尖，背部挺直",
        "focus": "股四头肌、臀大肌、核心",
        "benefits": ["增强下肢力量", "提升代谢", "改善体型"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "哑铃肩推", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 8, "goal_type": "muscle_gain",
        "muscle_group": "shoulder", "equipment": "dumbbell",
        "calories_burn_per_min": 6,
        "steps": ["坐姿，双手持哑铃于肩部", "将哑铃推过头顶",
                  "手臂伸直", "缓慢下降回到肩部"],
        "caution": "避免腰部过度伸展",
        "focus": "三角肌前束、中束",
        "benefits": ["增强肩部力量", "改善肩部线条"],
        "video_minutes": 2,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "弹力带划船", "category": "力量训练", "duration": "4 组 × 12 次",
        "level": "进阶", "minutes": 10, "goal_type": "muscle_gain",
        "muscle_group": "back", "equipment": "band",
        "calories_burn_per_min": 6,
        "steps": ["坐姿，弹力带套于双脚", "双手抓握弹力带",
                  "屈肘后拉至腹部", "缓慢回到起始位置"],
        "caution": "肩胛骨后缩，避免耸肩",
        "focus": "背阔肌、菱形肌",
        "benefits": ["增强背部力量", "改善体态"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "卧推", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 15, "goal_type": "muscle_gain",
        "muscle_group": "chest", "equipment": "barbell",
        "calories_burn_per_min": 6,
        "steps": ["仰卧于训练凳上", "双手正握杠铃与肩同宽",
                  "缓慢下降杠铃至胸部", "推起回到起始位置"],
        "caution": "肩胛骨收紧，避免腰部过度拱起，需保护者协助",
        "focus": "胸大肌、三角肌前束、肱三头肌",
        "benefits": ["增强上肢力量", "改善胸肌线条", "提升爆发力"],
        "video_minutes": 5,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "硬拉", "category": "力量训练", "duration": "4 组 × 8 次",
        "level": "进阶", "minutes": 15, "goal_type": "muscle_gain",
        "muscle_group": "back", "equipment": "barbell",
        "calories_burn_per_min": 8,
        "steps": ["杠铃置于脚前", "屈髋下蹲双手握杠",
                  "保持背部挺直", "伸髋伸膝站起"],
        "caution": "保持脊柱中立位，避免弓背，重量循序渐进",
        "focus": "竖脊肌、臀大肌、腘绳肌",
        "benefits": ["增强后链力量", "提升综合力量", "改善体态"],
        "video_minutes": 5,
        "bmi_range": "18.5-28.0",
    },
    {
        "name": "引体向上", "category": "力量训练", "duration": "4 组 × 8 次",
        "level": "进阶", "minutes": 10, "goal_type": "muscle_gain",
        "muscle_group": "back", "equipment": "bodyweight",
        "calories_burn_per_min": 8,
        "steps": ["双手宽握单杠", "身体悬垂",
                  "屈肘将下巴拉过杠", "缓慢下降回到起始位置"],
        "caution": "避免身体摆动借力，初学者可用弹力带辅助",
        "focus": "背阔肌、肱二头肌",
        "benefits": ["增强上肢拉力", "改善背部线条"],
        "video_minutes": 3,
        "bmi_range": "18.5-28.0",
    },
    {
        "name": "杠铃弯举", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 8, "goal_type": "muscle_gain",
        "muscle_group": "arms", "equipment": "barbell",
        "calories_burn_per_min": 6,
        "steps": ["双手反握杠铃与肩同宽", "上臂固定",
                  "屈肘将杠铃举至肩部", "缓慢下降回到起始位置"],
        "caution": "避免身体晃动借力，肘部固定",
        "focus": "肱二头肌",
        "benefits": ["增强手臂力量", "改善手臂线条"],
        "video_minutes": 2,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "三头下压", "category": "力量训练", "duration": "4 组 × 12 次",
        "level": "进阶", "minutes": 8, "goal_type": "muscle_gain",
        "muscle_group": "arms", "equipment": "machine",
        "calories_burn_per_min": 5,
        "steps": ["站立于绳索器械前", "双手握把下压",
                  "伸直手臂至底部", "缓慢回到起始位置"],
        "caution": "肘部固定紧贴身体，避免耸肩",
        "focus": "肱三头肌",
        "benefits": ["增强手臂力量", "改善手臂后侧线条"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "杠铃俯身划船", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 12, "goal_type": "muscle_gain",
        "muscle_group": "back", "equipment": "barbell",
        "calories_burn_per_min": 7,
        "steps": ["屈髋俯身，背部挺直", "双手正握杠铃",
                  "屈肘将杠铃拉至下腹", "缓慢下降回到起始位置"],
        "caution": "保持脊柱中立位，避免弓背",
        "focus": "背阔肌、菱形肌、斜方肌中下部",
        "benefits": ["增强背部厚度", "改善体态"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "保加利亚分腿蹲", "category": "力量训练", "duration": "4 组 × 10 次",
        "level": "进阶", "minutes": 12, "goal_type": "muscle_gain",
        "muscle_group": "legs", "equipment": "dumbbell",
        "calories_burn_per_min": 7,
        "steps": ["后脚置于训练凳上", "前脚向前一步",
                  "下蹲至前腿大腿与地面平行", "站起回到起始位置"],
        "caution": "前膝不超过脚尖，保持平衡",
        "focus": "股四头肌、臀大肌",
        "benefits": ["增强下肢力量", "改善单侧不平衡"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
]

# 减脂动作（fat_loss）
FAT_LOSS_EXERCISES = [
    {
        "name": "开合跳", "category": "有氧运动", "duration": "5 组 × 30 秒",
        "level": "基础", "minutes": 10, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 12,
        "steps": ["站立姿势", "跳跃同时双脚分开双手举过头顶",
                  "再次跳跃回到起始位置", "保持节奏"],
        "caution": "膝盖微屈，缓冲落地",
        "focus": "全身有氧",
        "benefits": ["快速提升心率", "高效燃脂", "提升心肺功能"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "高抬腿", "category": "有氧运动", "duration": "5 组 × 30 秒",
        "level": "进阶", "minutes": 8, "goal_type": "fat_loss",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 13,
        "steps": ["原地站立", "交替抬膝至大腿与地面平行", "保持快速节奏"],
        "caution": "保持核心收紧",
        "focus": "下肢有氧、核心",
        "benefits": ["高强度燃脂", "提升心肺功能"],
        "video_minutes": 2,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "波比跳", "category": "高强度间歇", "duration": "5 组 × 10 次",
        "level": "进阶", "minutes": 10, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 15,
        "steps": ["站立姿势", "下蹲双手撑地", "跳成俯卧撑姿势",
                  "完成一次俯卧撑", "跳回蹲姿", "跳起双手举过头顶"],
        "caution": "BMI 过高者慎做，避免关节冲击",
        "focus": "全身高强度",
        "benefits": ["高效燃脂", "全身力量训练", "提升心肺"],
        "video_minutes": 3,
        "bmi_range": "18.5-28.0",
    },
    {
        "name": "登山者", "category": "高强度间歇", "duration": "5 组 × 30 秒",
        "level": "进阶", "minutes": 8, "goal_type": "fat_loss",
        "muscle_group": "core", "equipment": "bodyweight",
        "calories_burn_per_min": 12,
        "steps": ["俯卧撑姿势", "交替将膝盖拉向胸部", "保持快速节奏"],
        "caution": "核心收紧，避免臀部抬高",
        "focus": "核心、有氧",
        "benefits": ["燃脂", "核心训练"],
        "video_minutes": 2,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "跳绳", "category": "有氧运动", "duration": "5 组 × 1 分钟",
        "level": "基础", "minutes": 15, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 13,
        "steps": ["双手握绳", "以腕力甩动跳绳",
                  "双脚轻跳过绳", "保持节奏"],
        "caution": "前脚掌着地，膝盖微屈缓冲",
        "focus": "全身有氧、小腿",
        "benefits": ["高效燃脂", "提升心肺功能", "增强协调性"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "椭圆机", "category": "有氧运动", "duration": "30 分钟",
        "level": "基础", "minutes": 30, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "machine",
        "calories_burn_per_min": 10,
        "steps": ["双脚踩踏板", "双手握把手",
                  "交替推拉", "保持均匀呼吸"],
        "caution": "保持躯干稳定，避免过度依赖把手",
        "focus": "全身有氧",
        "benefits": ["低冲击有氧", "保护膝关节", "高效燃脂"],
        "video_minutes": 5,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "慢跑", "category": "有氧运动", "duration": "30 分钟",
        "level": "基础", "minutes": 30, "goal_type": "fat_loss",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 10,
        "steps": ["保持身体直立", "前脚掌着地",
                  "肘部屈 90 度前后摆动", "均匀呼吸"],
        "caution": "选择合适跑鞋，BMI 过高者改为快走",
        "focus": "下肢有氧",
        "benefits": ["高效燃脂", "提升心肺功能", "改善代谢"],
        "video_minutes": 5,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "游泳", "category": "有氧运动", "duration": "30 分钟",
        "level": "进阶", "minutes": 30, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 11,
        "steps": ["选择适合泳姿（自由泳或蛙泳）", "保持身体流线型",
                  "协调呼吸与划水", "保持节奏"],
        "caution": "需具备游泳技能，避免空腹或饱腹下水",
        "focus": "全身有氧",
        "benefits": ["低冲击有氧", "全身锻炼", "改善心肺"],
        "video_minutes": 5,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "动感单车", "category": "有氧运动", "duration": "30 分钟",
        "level": "进阶", "minutes": 30, "goal_type": "fat_loss",
        "muscle_group": "legs", "equipment": "machine",
        "calories_burn_per_min": 12,
        "steps": ["调整座椅高度", "双手握把手",
                  "保持骑行节奏", "可调节阻力"],
        "caution": "调整合适座椅高度，避免膝盖过度弯曲",
        "focus": "下肢有氧",
        "benefits": ["高效燃脂", "提升心肺功能", "增强下肢耐力"],
        "video_minutes": 5,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "划船机", "category": "有氧运动", "duration": "20 分钟",
        "level": "进阶", "minutes": 20, "goal_type": "fat_loss",
        "muscle_group": "full_body", "equipment": "machine",
        "calories_burn_per_min": 11,
        "steps": ["坐姿，双脚踩踏板", "双手握把手",
                  "蹬腿后拉把手至腹部", "反向回到起始位置"],
        "caution": "保持脊柱中立，动作协调",
        "focus": "全身有氧",
        "benefits": ["全身燃脂", "增强后链力量", "提升心肺"],
        "video_minutes": 3,
        "bmi_range": "18.5-35.0",
    },
]

# 康复动作（rehab）—— 复用现有 rehab_exercises 数据
REHAB_EXERCISES = [
    {
        "name": "鸟狗式", "category": "核心稳定", "duration": "3 组 × 10 次",
        "level": "基础", "minutes": 5, "goal_type": "rehab",
        "muscle_group": "core", "equipment": "bodyweight",
        "calories_burn_per_min": 4,
        "steps": ["四足跪姿，双手撑地", "伸直右臂和左腿",
                  "保持脊柱中立位", "回到起始位置，换另一侧"],
        "caution": "保持脊柱中立，避免腰部下垂",
        "focus": "核心稳定与抗旋转控制",
        "benefits": ["提升核心稳定性", "改善腰背疼痛", "增强协调性"],
        "video_minutes": 3,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "死虫式", "category": "核心稳定", "duration": "3 组 × 10 次",
        "level": "基础", "minutes": 5, "goal_type": "rehab",
        "muscle_group": "core", "equipment": "bodyweight",
        "calories_burn_per_min": 4,
        "steps": ["仰卧，双臂垂直向上", "屈髋屈膝 90 度",
                  "伸直右臂和左腿", "回到起始位置，换另一侧"],
        "caution": "下背贴地，避免腰部拱起",
        "focus": "核心稳定与姿势改善",
        "benefits": ["核心力量", "改善姿势", "下背康复"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "髂腰肌拉伸", "category": "灵活性", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "rehab",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["弓步姿势，后腿膝盖着地", "骨盆前倾", "感受髂腰肌拉伸"],
        "caution": "保持上身直立，避免腰部过度前倾",
        "focus": "髂腰肌灵活性",
        "benefits": ["改善久坐不适", "提升髋部灵活性"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "弹力带肩外旋", "category": "康复训练", "duration": "3 组 × 12 次",
        "level": "基础", "minutes": 6, "goal_type": "rehab",
        "muscle_group": "shoulder", "equipment": "band",
        "calories_burn_per_min": 3,
        "steps": ["弹力带固定于身侧", "肘部屈 90 度贴身",
                  "前臂向外旋转", "缓慢回到起始位置"],
        "caution": "肘部紧贴身体，避免耸肩代偿",
        "focus": "冈下肌、小圆肌",
        "benefits": ["增强肩袖肌群", "改善肩关节稳定", "肩伤康复"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "臀桥", "category": "康复训练", "duration": "3 组 × 12 次",
        "level": "基础", "minutes": 6, "goal_type": "rehab",
        "muscle_group": "core", "equipment": "bodyweight",
        "calories_burn_per_min": 4,
        "steps": ["仰卧屈膝", "双脚与肩同宽",
                  "臀部发力上抬至身体成一条直线", "缓慢下降"],
        "caution": "臀部主导发力，避免腰部代偿",
        "focus": "臀大肌、核心",
        "benefits": ["增强臀肌", "改善腰背痛", "骨盆稳定"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "墙天使", "category": "康复训练", "duration": "3 组 × 10 次",
        "level": "基础", "minutes": 5, "goal_type": "rehab",
        "muscle_group": "back", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["背靠墙站立", "后脑勺、上背、臀部贴墙",
                  "双臂呈 90 度贴墙", "上下滑动双臂"],
        "caution": "保持各部位贴墙，避免腰部离开",
        "focus": "肩胛稳定、姿势纠正",
        "benefits": ["改善圆肩驼背", "增强肩胛稳定", "姿势纠正"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "蚌式开合", "category": "康复训练", "duration": "3 组 × 12 次",
        "level": "基础", "minutes": 5, "goal_type": "rehab",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["侧卧屈膝", "双脚并拢",
                  "上方膝盖向上打开", "缓慢回到起始位置"],
        "caution": "保持骨盆稳定，避免后倾",
        "focus": "臀中肌",
        "benefits": ["增强臀中肌", "改善膝外翻", "骨盆稳定"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "侧卧抬腿", "category": "康复训练", "duration": "3 组 × 12 次",
        "level": "基础", "minutes": 5, "goal_type": "rehab",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["侧卧身体成一条直线", "下方腿微屈",
                  "上方腿伸直抬起", "缓慢下降"],
        "caution": "保持骨盆稳定，避免翻动",
        "focus": "臀中肌、髋外展肌",
        "benefits": ["增强髋外展肌群", "改善骨盆稳定"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
]

# 柔韧动作（flexibility）
FLEXIBILITY_EXERCISES = [
    {
        "name": "猫牛式", "category": "柔韧训练", "duration": "3 组 × 10 次",
        "level": "基础", "minutes": 5, "goal_type": "flexibility",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["四足跪姿", "吸气时腹部下沉抬头（牛式）",
                  "呼气时弓背低头（猫式）", "缓慢交替"],
        "caution": "动作缓慢，配合呼吸",
        "focus": "脊柱灵活性",
        "benefits": ["改善脊柱灵活性", "缓解背部紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "下犬式", "category": "柔韧训练", "duration": "3 组 × 30 秒",
        "level": "基础", "minutes": 5, "goal_type": "flexibility",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 4,
        "steps": ["双手双脚撑地", "臀部上抬形成倒 V 字",
                  "脚跟尽量贴地", "保持 30 秒"],
        "caution": "膝盖可微屈，避免过度拉伸",
        "focus": "全身后链拉伸",
        "benefits": ["拉伸腿后侧", "增强上肢力量", "改善体态"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "股四头肌拉伸", "category": "柔韧训练", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "flexibility",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["站立，单手扶墙", "另一只手抓住同侧脚踝",
                  "将脚跟拉向臀部", "保持 30 秒，换另一侧"],
        "caution": "膝盖指向地面，避免外展",
        "focus": "股四头肌拉伸",
        "benefits": ["改善腿部柔韧性", "缓解运动后紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "腘绳肌拉伸", "category": "柔韧训练", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "flexibility",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["坐姿，一腿伸直", "另一腿屈膝贴于伸直腿内侧",
                  "上身前倾", "保持 30 秒，换另一侧"],
        "caution": "保持背部挺直，避免弓背",
        "focus": "腘绳肌",
        "benefits": ["改善腿后侧柔韧性", "缓解腰部紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "胸椎旋转", "category": "柔韧训练", "duration": "2 组 × 10 次",
        "level": "基础", "minutes": 5, "goal_type": "flexibility",
        "muscle_group": "full_body", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["侧卧屈膝", "上方手伸向对侧",
                  "胸椎旋转打开", "回到起始位置"],
        "caution": "保持骨盆稳定，仅旋转胸椎",
        "focus": "胸椎灵活性",
        "benefits": ["改善胸椎活动度", "缓解背部紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "坐姿体前屈", "category": "柔韧训练", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "flexibility",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 3,
        "steps": ["坐姿双腿伸直", "上身前倾",
                  "双手触碰脚尖", "保持 30 秒"],
        "caution": "保持膝盖伸直，避免弓背",
        "focus": "腘绳肌、小腿",
        "benefits": ["改善下肢柔韧性", "缓解腰部紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "小腿拉伸", "category": "柔韧训练", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "flexibility",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 2,
        "steps": ["弓步姿势，后腿伸直", "后脚跟着地",
                  "身体前倾感受小腿拉伸", "保持 30 秒，换另一侧"],
        "caution": "后脚跟不要离地",
        "focus": "腓肠肌、比目鱼肌",
        "benefits": ["改善小腿柔韧性", "预防跟腱损伤"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "肩部拉伸", "category": "柔韧训练", "duration": "2 组 × 30 秒",
        "level": "基础", "minutes": 4, "goal_type": "flexibility",
        "muscle_group": "shoulder", "equipment": "bodyweight",
        "calories_burn_per_min": 2,
        "steps": ["将一只手臂横过胸前", "另一只手轻压",
                  "感受肩部拉伸", "保持 30 秒，换另一侧"],
        "caution": "保持肩部放松，避免耸肩",
        "focus": "三角肌后束",
        "benefits": ["改善肩部柔韧性", "缓解肩颈紧张"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
]

# 维持动作（maintenance）
MAINTENANCE_EXERCISES = [
    {
        "name": "平板支撑", "category": "核心稳定", "duration": "3 组 × 30 秒",
        "level": "基础", "minutes": 5, "goal_type": "maintenance",
        "muscle_group": "core", "equipment": "bodyweight",
        "calories_burn_per_min": 5,
        "steps": ["前臂撑地", "身体保持一条直线", "核心收紧", "保持呼吸"],
        "caution": "避免塌腰或翘臀",
        "focus": "核心稳定性",
        "benefits": ["增强核心", "改善体态", "提升耐力"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "靠墙静蹲", "category": "力量训练", "duration": "3 组 × 30 秒",
        "level": "基础", "minutes": 5, "goal_type": "maintenance",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 5,
        "steps": ["背靠墙站立", "缓慢下蹲至大腿与地面平行", "保持 30 秒"],
        "caution": "膝盖不超过脚尖",
        "focus": "股四头肌耐力",
        "benefits": ["增强腿部耐力", "保护膝关节"],
        "video_minutes": 2,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "快走", "category": "有氧运动", "duration": "30 分钟",
        "level": "基础", "minutes": 30, "goal_type": "maintenance",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 6,
        "steps": ["保持上身挺直", "加快步伐至微微出汗",
                  "手臂自然摆动", "保持均匀呼吸"],
        "caution": "选择合适鞋子，避免过度疲劳",
        "focus": "下肢有氧",
        "benefits": ["维持心肺功能", "改善代谢", "低冲击运动"],
        "video_minutes": 5,
        "bmi_range": "18.5-35.0",
    },
    {
        "name": "爬楼梯", "category": "有氧运动", "duration": "15 分钟",
        "level": "基础", "minutes": 15, "goal_type": "maintenance",
        "muscle_group": "legs", "equipment": "bodyweight",
        "calories_burn_per_min": 9,
        "steps": ["保持上身挺直", "一步一阶或两阶",
                  "下楼梯时缓慢", "保持呼吸"],
        "caution": "膝关节有损伤者慎做，下楼可乘电梯",
        "focus": "股四头肌、臀大肌",
        "benefits": ["增强下肢力量", "提升心肺功能"],
        "video_minutes": 3,
        "bmi_range": "18.5-30.0",
    },
    {
        "name": "骑行", "category": "有氧运动", "duration": "30 分钟",
        "level": "基础", "minutes": 30, "goal_type": "maintenance",
        "muscle_group": "legs", "equipment": "machine",
        "calories_burn_per_min": 8,
        "steps": ["调整座椅高度", "保持上身前倾",
                  "踩踏节奏均匀", "保持呼吸"],
        "caution": "调整合适座椅高度，注意交通安全",
        "focus": "下肢有氧",
        "benefits": ["维持心肺功能", "增强下肢力量", "低冲击"],
        "video_minutes": 5,
        "bmi_range": "18.5-35.0",
    },
]


def main():
    """主入口"""
    print("=" * 60)
    print("康复训练动作库整理")
    print("=" * 60)

    all_exercises = (
        MUSCLE_GAIN_EXERCISES
        + FAT_LOSS_EXERCISES
        + REHAB_EXERCISES
        + FLEXIBILITY_EXERCISES
        + MAINTENANCE_EXERCISES
    )

    output_file = OUTPUT_DIR / "rehab_exercises.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(all_exercises, f, ensure_ascii=False, indent=2)

    print(f"[INFO] 已保存到 {output_file}")
    print(f"[INFO] 共 {len(all_exercises)} 个动作")

    # 统计
    by_goal = {}
    for ex in all_exercises:
        goal = ex["goal_type"]
        by_goal[goal] = by_goal.get(goal, 0) + 1
    print(f"[INFO] 按目标分类: {by_goal}")


if __name__ == "__main__":
    main()
