CREATE TABLE IF NOT EXISTS user_diet_preferences (
  user_id INT PRIMARY KEY,
  diet_style VARCHAR(32),
  disliked_foods TEXT,
  preferred_cuisine VARCHAR(64),
  daily_meal_count INT DEFAULT 3,
  avoid_spicy TINYINT(1) NOT NULL DEFAULT 0,
  avoid_cold TINYINT(1) NOT NULL DEFAULT 0,
  vegetarian TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE user_diet_preferences
  ADD COLUMN IF NOT EXISTS avoid_spicy TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avoid_cold TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vegetarian TINYINT(1) NOT NULL DEFAULT 0;
